controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (jumps < 2) {
        mySprite.vy += -300
        jumps += 1
    }
})
scene.onHitWall(SpriteKind.Player, function (sprite, location) {
	
})
let jumps = 0
let mySprite: Sprite = null
tiles.setTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ..............eee...
    ...........eeee2ee..
    .......eeeeeeeeeee..
    .....eeeeeeeeee...3.
    .e..eeeeeeeeee......
    ..eeeeeeeeeee.......
    ...eeeee..eee.......
    ..eeeee...eee.......
    ..eeeee..ee.e.......
    ..ee.ee..e..e.......
    ..ee.ee..e..e.......
    ..ee.e...e..e.......
    ..e..e...e..e.......
    .ee.e....e..ee......
    .e..e.....e..e......
    .e..e.....e...e.....
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 0)
scene.cameraFollowSprite(mySprite)
mySprite.ay = 1000
jumps = 0
tiles.placeOnTile(mySprite, tiles.getTileLocation(0, 12))
forever(function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        jumps = 0
    }
})
