controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.vy += -300
    jumps += 1
})
let mySprite: Sprite = null
tiles.setTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ..............eee...
    ...........eeee2ee..
    .......eeeeeeeeeee..
    .....eeeeeeeeee...3.
    .e..eeeeeeeeee......
    ..eeeeeeeeeee.......
    ...eeeee..eee.......
    ..eeeee...eee.......
    ..eeeee..ee.e.......
    ..ee.ee..e..e.......
    ..ee.ee..e..e.......
    ..ee.e...e..e.......
    ..e..e...e..e.......
    .ee.e....e..ee......
    .e..e.....e..e......
    .e..e.....e...e.....
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 0)
mySprite.ay = 1000
scene.cameraFollowSprite(mySprite)
let jumps = 0
forever(function () {
    if (jumps < 2) {
    	
    }
})
